import React from 'react';
import { BrainCircuit, FlaskConical, Info } from 'lucide-react';
import type { SearchMode } from '../lib/modes';

interface AnswerPanelProps {
  mode: SearchMode;
  answer: string | null;
  /** Backend explanation when no answer could be grounded (never invented text). */
  note?: string | undefined;
  /** Number of retrieved passages the RAG pipeline actually used. */
  passages?: number | undefined;
}

const MODE_COPY: Record<
  SearchMode,
  { title: string; blurb: string; icon: React.ComponentType<{ className?: string }> }
> = {
  web: { title: 'Answer', blurb: '', icon: BrainCircuit },
  ai: {
    title: 'AI answer',
    blurb: 'Generated by the SEEK RAG pipeline from the cited sources below.',
    icon: BrainCircuit,
  },
  research: {
    title: 'Research synthesis',
    blurb:
      'Generated synthesis. The evidence list below is the retrieved corpus material it was grounded on.',
    icon: FlaskConical,
  },
  code: { title: 'Answer', blurb: '', icon: BrainCircuit },
};

/**
 * Grounded-answer panel for the AI Answers / Research modes (Phase 9).
 *
 * It renders only what the backend returned. When no answer could be grounded
 * the panel states that explicitly and shows the backend's own reason - it never
 * substitutes placeholder or invented text.
 */
export const AnswerPanel: React.FC<AnswerPanelProps> = ({ mode, answer, note, passages }) => {
  if (mode !== 'ai' && mode !== 'research') return null;

  const copy = MODE_COPY[mode];
  const Icon = copy.icon;
  const hasAnswer = typeof answer === 'string' && answer.trim().length > 0;

  return (
    <section
      aria-label={copy.title}
      className="rounded-xl border border-seek-border bg-gradient-to-br from-indigo-950/40 via-seek-card to-seek-card p-5 shadow-sm sm:p-6"
    >
      <div className="flex flex-wrap items-center gap-2">
        <span className="inline-flex items-center gap-2 rounded-lg bg-indigo-600/20 px-2.5 py-1 text-sm font-semibold text-indigo-200">
          <Icon className="h-4 w-4" aria-hidden="true" />
          {copy.title}
        </span>
        {hasAnswer && (
          <span className="rounded-full border border-emerald-800/60 bg-emerald-950/40 px-2.5 py-0.5 text-[11px] font-medium text-emerald-300">
            grounded in SEEK sources
          </span>
        )}
        {typeof passages === 'number' && passages > 0 && (
          <span className="font-mono text-[11px] text-gray-500">
            {passages} passage{passages === 1 ? '' : 's'} used
          </span>
        )}
      </div>

      {hasAnswer ? (
        <p className="mt-4 whitespace-pre-wrap text-[15px] leading-relaxed text-gray-200">
          {answer}
        </p>
      ) : (
        <div className="mt-4 rounded-lg border border-amber-900/40 bg-amber-950/20 p-4">
          <p className="flex items-start gap-2 text-sm font-medium text-amber-200">
            <Info className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
            No answer could be generated for this query.
          </p>
          {note ? (
            <p className="mt-1 pl-6 text-sm text-amber-200/80">{note}</p>
          ) : (
            <p className="mt-1 pl-6 text-sm text-amber-200/80">
              SEEK never invents an answer - the reason reported by the backend is shown here
              instead.
            </p>
          )}
        </div>
      )}

      {hasAnswer && copy.blurb && (
        <p className="mt-3 text-xs leading-relaxed text-gray-500">{copy.blurb}</p>
      )}
    </section>
  );
};

export default AnswerPanel;